# Path to config-classes.xml (relative to the JVM's working directory when
# you run the app - typically the project root, next to pom.xml).
app.config-classes-xml-path=E:/tmp/finalconfigclasses/finalconfigclasses-framework-java17-zk/finalconfigclasses-framework/src/main/resources/config-classes.xml

server.port=8081
