//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated by a tool.
    //     Developed by Hossein Samadzadegan.
    //     Version:2.0
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by FinalConfigClasses, Version=2.0.
//
package Land;

import finalconfigclasses.bean.PropertyUpdate;
import finalconfigclasses.cfg.ConfigBean;
import finalconfigclasses.cfg.ConfigBeanUpdateEvent;
import finalconfigclasses.cfg.ConfigDiffHelper;
import finalconfigclasses.cfg.ConfigPropertyUpdate;




/**
* This class computes difference between two instances of
* class LandConfig. You may create a copy(clone) of an instance
* of class LandConfig, then modify cloned object, and want to
* compute changes between original instance and cloned object
* (for validations purposes).
* This class would help you to do that.
*
* Original object is named 'sourceBean'(see body of class).
* Cloned version is named 'proposedBean'(see body of class).
*
* You can access to functionality of this class like this:
*
*        LandConfig foo = new LandConfig(...);
*        LandConfigDiffHelper diffHelper =
*			 (LandConfigDiffHelper)foo._newDiffHelper();
*/
public class LandConfigDiffHelper extends ConfigDiffHelper {



public LandConfigDiffHelper(ConfigBean sourceBean) {
super(sourceBean);
}



protected void _computeDiff(ConfigBean proposedBean) {
super._computeDiff(proposedBean);

LandConfig _bean = (LandConfig) bean;
LandConfig _proposedBean = (LandConfig) proposedBean;

computeDiff("dbIsWinAuth",
_bean.getDbIsWinAuth(),
_proposedBean.getDbIsWinAuth(),
_bean.isDynamic("dbIsWinAuth"));
computeDiff("serverIp",
_bean.getServerIp(),
_proposedBean.getServerIp(),
_bean.isDynamic("serverIp"));
computeDiff("dbPort",
_bean.getDbPort(),
_proposedBean.getDbPort(),
_bean.isDynamic("dbPort"));
computeDiff("dbInstanceName",
_bean.getDbInstanceName(),
_proposedBean.getDbInstanceName(),
_bean.isDynamic("dbInstanceName"));
computeDiff("dbName",
_bean.getDbName(),
_proposedBean.getDbName(),
_bean.isDynamic("dbName"));
computeDiff("dbUser",
_bean.getDbUser(),
_proposedBean.getDbUser(),
_bean.isDynamic("dbUser"));
computeDiff("dbUserPass",
_bean.getDbUserPass(),
_proposedBean.getDbUserPass(),
_bean.isDynamic("dbUserPass"));
computeDiff("picDir",
_bean.getPicDir(),
_proposedBean.getPicDir(),
_bean.isDynamic("picDir"));
computeDiff("pageSize",
_bean.getPageSize(),
_proposedBean.getPageSize(),
_bean.isDynamic("pageSize"));

}



protected void applyPropertyUpdate(ConfigBeanUpdateEvent evt, ConfigPropertyUpdate update) {

LandConfig original;
LandConfig proposed;
String prop;
PropertyUpdate.UpdateType type;
try
{
original = (LandConfig)evt.getSourceBean();
proposed = (LandConfig)evt.getProposedBean();
prop = update.getPropertyName();
type = update.getUpdateType();
if(update.isDerivedUpdate())
return;
if(update.isUnsetUpdate()) {
original.unSet(prop);
return;
}
}
catch (RuntimeException e)
{
throw e;
}
catch(Exception e)
{
throw (Error)(new AssertionError("Impossible Exception")).initCause(e);
}

        if(prop.equals("dbIsWinAuth")) {
        original.setDbIsWinAuth(proposed.getDbIsWinAuth());
    }
        else if(prop.equals("serverIp")) {
        original.setServerIp(proposed.getServerIp());
    }
        else if(prop.equals("dbPort")) {
        original.setDbPort(proposed.getDbPort());
    }
        else if(prop.equals("dbInstanceName")) {
        original.setDbInstanceName(proposed.getDbInstanceName());
    }
        else if(prop.equals("dbName")) {
        original.setDbName(proposed.getDbName());
    }
        else if(prop.equals("dbUser")) {
        original.setDbUser(proposed.getDbUser());
    }
        else if(prop.equals("dbUserPass")) {
        original.setDbUserPass(proposed.getDbUserPass());
    }
        else if(prop.equals("picDir")) {
        original.setPicDir(proposed.getPicDir());
    }
        else if(prop.equals("pageSize")) {
        original.setPageSize(proposed.getPageSize());
    }
else {
super.applyPropertyUpdate(evt, update);
}
}
}//end of class