//------------------------------------------------------------------------------
// <auto-generated>
	//     This code was generated by a tool.
	//     Developed by Hossein Samadzadegan.
	//     Version:3.0 (Java 17 / ZooKeeper edition)
	//
	//     Changes to this file may cause incorrect behavior and will be lost if
	//     the code is regenerated.
	// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by FinalConfigClasses, Version=3.0.
//
package Land;

import java.util.*;
import java.util.concurrent.locks.ReentrantReadWriteLock;

import finalconfigclasses.cfg.*;
import finalconfigclasses.cfg.zk.ZkAttrSnapshot;
import finalconfigclasses.cfg.zk.ZkConfigStore;
import finalconfigclasses.cfg.zk.ZkConfigManager;




/**
* This class use solution (A) for dead lock prevention.
* ... (javadoc unchanged)
*/
public class LandConfig extends BaseConfigBean {

private static final String CLASS_KEY = "land-config";



private static final String KEY_0 = "db-is-win-auth";
private static final String KEY_1 = "server-ip";
private static final String KEY_2 = "db-port";
private static final String KEY_3 = "db-instance-name";
private static final String KEY_4 = "db-name";
private static final String KEY_5 = "db-user";
private static final String KEY_6 = "db-user-pass";
private static final String KEY_7 = "pic-dir";
private static final String KEY_8 = "page-size";



public LandConfig() {
}

public LandConfig(final HashMap<String, Object> defValue) {
super(defValue);
}

public LandConfig(final HashMap<String, Object> defValue,
final HashMap<String, Object> dynaProp) {
super(defValue, dynaProp);
}

public LandConfig(final HashMap<String, Object> defValue,
final HashMap<String, Object> dynaProp,
final ConfigBean parent) {
super(defValue, dynaProp, parent);
}

public LandConfig(final HashMap<String, Object> defValue,
final String propertiesFile,
/*final XmlContainer container,*/
final String lockID,
final ReentrantReadWriteLock propertiesLock,
final String document,
final String name,
final String keyPrefix) {
super(defValue, propertiesFile, lockID, propertiesLock, document, name, keyPrefix);
}

public LandConfig(final HashMap<String, Object> defValue,
final ConfigBean parent,
final String propertiesFile,
/*final XmlContainer container,*/
final String lockID,
final ReentrantReadWriteLock propertiesLock,
final String document,
final String name,
final String keyPrefix) {
super(defValue, parent, propertiesFile, lockID, propertiesLock, document, name, keyPrefix);
}

public LandConfig(final HashMap<String, Object> defValue,
final HashMap<String, Object> dynaProp,
final String propertiesFile,
/*final XmlContainer container,*/
final String lockID,
final ReentrantReadWriteLock propertiesLock,
final String document,
final String name,
final String keyPrefix) {
super(defValue, dynaProp, propertiesFile, lockID, propertiesLock, document, name, keyPrefix);
}

public LandConfig(final HashMap<String, Object> defValue,
final HashMap<String, Object> dynaProp,
final ConfigBean parent,
final String propertiesFile,
/*final XmlContainer container,*/
final String lockID,
final ReentrantReadWriteLock propertiesLock,
final String document,
final String name,
final String keyPrefix) {
super(defValue, dynaProp, parent, propertiesFile, lockID, propertiesLock, document, name, keyPrefix);
}

//full constructor which should be defined for correct cloning
public LandConfig(final String beanID,
final HashMap<String, Object> defValue,
final HashMap<String, Object> dynaProp,
final ConfigBean parent,
final String propertiesFile,
/*final XmlContainer container,*/
final String lockID,
final ReentrantReadWriteLock propertiesLock,
final String document,
final String name,
final String keyPrefix) {
super(beanID, defValue, dynaProp, parent, propertiesFile, lockID, propertiesLock, document, name, keyPrefix);
}




	public boolean getDbIsWinAuth() {
	readLock();
	try {
	return (Boolean) getAttr("dbIsWinAuth");
	} finally {
	readUnlock();
	}
	}

	public void setDbIsWinAuth(boolean dbIsWinAuth) {
		Boolean oldVal = null;
	writeLock();
	try {
	oldVal = (Boolean) getAttr("dbIsWinAuth");
	setAttr("dbIsWinAuth", dbIsWinAuth);
	_postSet("dbIsWinAuth", oldVal, dbIsWinAuth);
	} finally {
	writeUnlock();
	}
	//calling listeners out of lock block to avoid dead-lock.
	firePropertyChange("dbIsWinAuth", oldVal, dbIsWinAuth);
	}

	public String getServerIp() {
	readLock();
	try {
	return (String) getAttr("serverIp");
	} finally {
	readUnlock();
	}
	}

	public void setServerIp(String serverIp) {
		String oldVal = null;
	writeLock();
	try {
	oldVal = (String) getAttr("serverIp");
	setAttr("serverIp", serverIp);
	_postSet("serverIp", oldVal, serverIp);
	} finally {
	writeUnlock();
	}
	//calling listeners out of lock block to avoid dead-lock.
	firePropertyChange("serverIp", oldVal, serverIp);
	}

	public Integer getDbPort() {
	readLock();
	try {
	return (Integer) getAttr("dbPort");
	} finally {
	readUnlock();
	}
	}

	public void setDbPort(Integer dbPort) {
		Integer oldVal = null;
	writeLock();
	try {
	oldVal = (Integer) getAttr("dbPort");
	setAttr("dbPort", dbPort);
	_postSet("dbPort", oldVal, dbPort);
	} finally {
	writeUnlock();
	}
	//calling listeners out of lock block to avoid dead-lock.
	firePropertyChange("dbPort", oldVal, dbPort);
	}

	public String getDbInstanceName() {
	readLock();
	try {
	return (String) getAttr("dbInstanceName");
	} finally {
	readUnlock();
	}
	}

	public void setDbInstanceName(String dbInstanceName) {
		String oldVal = null;
	writeLock();
	try {
	oldVal = (String) getAttr("dbInstanceName");
	setAttr("dbInstanceName", dbInstanceName);
	_postSet("dbInstanceName", oldVal, dbInstanceName);
	} finally {
	writeUnlock();
	}
	//calling listeners out of lock block to avoid dead-lock.
	firePropertyChange("dbInstanceName", oldVal, dbInstanceName);
	}

	public String getDbName() {
	readLock();
	try {
	return (String) getAttr("dbName");
	} finally {
	readUnlock();
	}
	}

	public void setDbName(String dbName) {
		String oldVal = null;
	writeLock();
	try {
	oldVal = (String) getAttr("dbName");
	setAttr("dbName", dbName);
	_postSet("dbName", oldVal, dbName);
	} finally {
	writeUnlock();
	}
	//calling listeners out of lock block to avoid dead-lock.
	firePropertyChange("dbName", oldVal, dbName);
	}

	public String getDbUser() {
	readLock();
	try {
	return (String) getAttr("dbUser");
	} finally {
	readUnlock();
	}
	}

	public void setDbUser(String dbUser) {
		String oldVal = null;
	writeLock();
	try {
	oldVal = (String) getAttr("dbUser");
	setAttr("dbUser", dbUser);
	_postSet("dbUser", oldVal, dbUser);
	} finally {
	writeUnlock();
	}
	//calling listeners out of lock block to avoid dead-lock.
	firePropertyChange("dbUser", oldVal, dbUser);
	}

	public String getDbUserPass() {
	readLock();
	try {
	return (String) getAttr("dbUserPass");
	} finally {
	readUnlock();
	}
	}

	public void setDbUserPass(String dbUserPass) {
		String oldVal = null;
	writeLock();
	try {
	oldVal = (String) getAttr("dbUserPass");
	setAttr("dbUserPass", dbUserPass);
	_postSet("dbUserPass", oldVal, dbUserPass);
	} finally {
	writeUnlock();
	}
	//calling listeners out of lock block to avoid dead-lock.
	firePropertyChange("dbUserPass", oldVal, dbUserPass);
	}

	public String getPicDir() {
	readLock();
	try {
	return (String) getAttr("picDir");
	} finally {
	readUnlock();
	}
	}

	public void setPicDir(String picDir) {
		String oldVal = null;
	writeLock();
	try {
	oldVal = (String) getAttr("picDir");
	setAttr("picDir", picDir);
	_postSet("picDir", oldVal, picDir);
	} finally {
	writeUnlock();
	}
	//calling listeners out of lock block to avoid dead-lock.
	firePropertyChange("picDir", oldVal, picDir);
	}

	public int getPageSize() {
	readLock();
	try {
	return (Integer) getAttr("pageSize");
	} finally {
	readUnlock();
	}
	}

	public void setPageSize(int pageSize) {
		Integer oldVal = null;
	writeLock();
	try {
	oldVal = (Integer) getAttr("pageSize");
	setAttr("pageSize", pageSize);
	_postSet("pageSize", oldVal, pageSize);
	} finally {
	writeUnlock();
	}
	//calling listeners out of lock block to avoid dead-lock.
	firePropertyChange("pageSize", oldVal, pageSize);
	}







public LandConfigDiffHelper _newDiffHelper() {
	LandConfigDiffHelper helper = new LandConfigDiffHelper(this);
return helper;
}

public String _getXPath() {
if(_getParent() == null) {
return eval(_getKeyPrefix(), CLASS_KEY, _getName());
} else {
return _getParent()._getXPath() + "/" + eval(_getKeyPrefix(), CLASS_KEY, _getName());
}
}



	public void load() throws ConfigException {
		Boolean oldVal_0 = null, newVal_0 = null;
		String oldVal_1 = null, newVal_1 = null;
		Integer oldVal_2 = null, newVal_2 = null;
		String oldVal_3 = null, newVal_3 = null;
		String oldVal_4 = null, newVal_4 = null;
		String oldVal_5 = null, newVal_5 = null;
		String oldVal_6 = null, newVal_6 = null;
		String oldVal_7 = null, newVal_7 = null;
		Integer oldVal_8 = null, newVal_8 = null;

		boolean notify_0 = false;
		boolean notify_1 = false;
		boolean notify_2 = false;
		boolean notify_3 = false;
		boolean notify_4 = false;
		boolean notify_5 = false;
		boolean notify_6 = false;
		boolean notify_7 = false;
		boolean notify_8 = false;

		writeLock();
		try {
		try {
			// "flexible" mode: create the znode (and any missing parents) if it
			// does not exist yet, rather than failing.
			ZkAttrSnapshot snap = ZkConfigStore.loadAttributes(
					ZkConfigManager.getInstance().getClient(),
					_getPropertiesFile(), _getDocument(), _getXPath(), true);

			if(snap.isLoaded()) {
			Boolean defVal_0 = (Boolean) getDefValue("dbIsWinAuth");
			boolean isSet_0 = snap.isSet("dbIsWinAuth");
			newVal_0 = isSet_0 ? (Boolean) snap.getValue("dbIsWinAuth") : defVal_0;
			oldVal_0 = (Boolean) getAttr("dbIsWinAuth");
			setAttr("dbIsWinAuth", newVal_0);
	        _loadMarkSet("dbIsWinAuth", isSet_0);
	        notify_0 = true;
			String defVal_1 = (String) getDefValue("serverIp");
			boolean isSet_1 = snap.isSet("serverIp");
			newVal_1 = isSet_1 ? (String) snap.getValue("serverIp") : defVal_1;
			oldVal_1 = (String) getAttr("serverIp");
			setAttr("serverIp", newVal_1);
	        _loadMarkSet("serverIp", isSet_1);
	        notify_1 = true;
			Integer defVal_2 = (Integer) getDefValue("dbPort");
			boolean isSet_2 = snap.isSet("dbPort");
			newVal_2 = isSet_2 ? (Integer) snap.getValue("dbPort") : defVal_2;
			oldVal_2 = (Integer) getAttr("dbPort");
			setAttr("dbPort", newVal_2);
	        _loadMarkSet("dbPort", isSet_2);
	        notify_2 = true;
			String defVal_3 = (String) getDefValue("dbInstanceName");
			boolean isSet_3 = snap.isSet("dbInstanceName");
			newVal_3 = isSet_3 ? (String) snap.getValue("dbInstanceName") : defVal_3;
			oldVal_3 = (String) getAttr("dbInstanceName");
			setAttr("dbInstanceName", newVal_3);
	        _loadMarkSet("dbInstanceName", isSet_3);
	        notify_3 = true;
			String defVal_4 = (String) getDefValue("dbName");
			boolean isSet_4 = snap.isSet("dbName");
			newVal_4 = isSet_4 ? (String) snap.getValue("dbName") : defVal_4;
			oldVal_4 = (String) getAttr("dbName");
			setAttr("dbName", newVal_4);
	        _loadMarkSet("dbName", isSet_4);
	        notify_4 = true;
			String defVal_5 = (String) getDefValue("dbUser");
			boolean isSet_5 = snap.isSet("dbUser");
			newVal_5 = isSet_5 ? (String) snap.getValue("dbUser") : defVal_5;
			oldVal_5 = (String) getAttr("dbUser");
			setAttr("dbUser", newVal_5);
	        _loadMarkSet("dbUser", isSet_5);
	        notify_5 = true;
			String defVal_6 = (String) getDefValue("dbUserPass");
			boolean isSet_6 = snap.isSet("dbUserPass");
			newVal_6 = isSet_6 ? (String) snap.getValue("dbUserPass") : defVal_6;
			oldVal_6 = (String) getAttr("dbUserPass");
			setAttr("dbUserPass", newVal_6);
	        _loadMarkSet("dbUserPass", isSet_6);
	        notify_6 = true;
			String defVal_7 = (String) getDefValue("picDir");
			boolean isSet_7 = snap.isSet("picDir");
			newVal_7 = isSet_7 ? (String) snap.getValue("picDir") : defVal_7;
			oldVal_7 = (String) getAttr("picDir");
			setAttr("picDir", newVal_7);
	        _loadMarkSet("picDir", isSet_7);
	        notify_7 = true;
			Integer defVal_8 = (Integer) getDefValue("pageSize");
			boolean isSet_8 = snap.isSet("pageSize");
			newVal_8 = isSet_8 ? (Integer) snap.getValue("pageSize") : defVal_8;
			oldVal_8 = (Integer) getAttr("pageSize");
			setAttr("pageSize", newVal_8);
	        _loadMarkSet("pageSize", isSet_8);
	        notify_8 = true;
			}
		} catch(ConfigException ce) {
			throw ce;
		} catch (Exception e) {			
			throw new ConfigException(e);
		}
		} finally {
			writeUnlock();
		}
		
		//calling listeners out of lock block to avoid dead-lock.
		if(notify_0)
			firePropertyChange("dbIsWinAuth", oldVal_0, newVal_0);		
		if(notify_1)
			firePropertyChange("serverIp", oldVal_1, newVal_1);		
		if(notify_2)
			firePropertyChange("dbPort", oldVal_2, newVal_2);		
		if(notify_3)
			firePropertyChange("dbInstanceName", oldVal_3, newVal_3);		
		if(notify_4)
			firePropertyChange("dbName", oldVal_4, newVal_4);		
		if(notify_5)
			firePropertyChange("dbUser", oldVal_5, newVal_5);		
		if(notify_6)
			firePropertyChange("dbUserPass", oldVal_6, newVal_6);		
		if(notify_7)
			firePropertyChange("picDir", oldVal_7, newVal_7);		
		if(notify_8)
			firePropertyChange("pageSize", oldVal_8, newVal_8);		
	}
	
	public void save() throws ConfigException {
		writeLock();
		try {
		try {
			LinkedHashMap<String, Object> values = new LinkedHashMap<String, Object>();
			LinkedHashMap<String, Boolean> setFlags = new LinkedHashMap<String, Boolean>();
			
			values.put("dbIsWinAuth", getDbIsWinAuth());
			setFlags.put("dbIsWinAuth", _isSet("dbIsWinAuth"));
			values.put("serverIp", getServerIp());
			setFlags.put("serverIp", _isSet("serverIp"));
			values.put("dbPort", getDbPort());
			setFlags.put("dbPort", _isSet("dbPort"));
			values.put("dbInstanceName", getDbInstanceName());
			setFlags.put("dbInstanceName", _isSet("dbInstanceName"));
			values.put("dbName", getDbName());
			setFlags.put("dbName", _isSet("dbName"));
			values.put("dbUser", getDbUser());
			setFlags.put("dbUser", _isSet("dbUser"));
			values.put("dbUserPass", getDbUserPass());
			setFlags.put("dbUserPass", _isSet("dbUserPass"));
			values.put("picDir", getPicDir());
			setFlags.put("picDir", _isSet("picDir"));
			values.put("pageSize", getPageSize());
			setFlags.put("pageSize", _isSet("pageSize"));

			// "flexible" mode: create the znode (and any missing parents) if it
			// does not exist yet, rather than failing.
			ZkConfigStore.saveAttributes(
					ZkConfigManager.getInstance().getClient(),
					_getPropertiesFile(), _getDocument(), _getXPath(), values, setFlags, true);
		} catch(ConfigException ce) {
			throw ce;
		} catch (Exception e) {
			throw new ConfigException(e);
		}
		} finally {
			writeUnlock();
		}
	}
}//end of class