package finalconfigclasses.cfg.model;

/**
 * Describes a single simple ("attribute") field of a generated config class,
 * as declared by an {@code &lt;attribute&gt;} element inside the config-classes
 * description XML (see config-classes.xsd).
 *
 * This class used to be generated by the JAXB (javax.xml.bind) compiler, but
 * javax.xml.bind was removed from the JDK starting with Java 11 and is no
 * longer available on the Java 17 runtime classpath by default. It is now a
 * plain POJO, (de)serialized directly from/to the description XML using
 * XStream (see {@link finalconfigclasses.cfg.model.ConfigModelIO}).
 */
public class Attribute {

	private String isArray;
	private String key;
	private String name;
	private String type;

	public Attribute() {
	}

	public Attribute(String name, String type, String key, String isArray) {
		this.name = name;
		this.type = type;
		this.key = key;
		this.isArray = isArray;
	}

	/**
	 * @return "true"/"false" as a string, defaulting to "false" when unset
	 *         (mirrors the original JAXB default-value semantics).
	 */
	public String getIsArray() {
		if (isArray == null) {
			return "false";
		} else {
			return isArray;
		}
	}

	public void setIsArray(String value) {
		this.isArray = value;
	}

	public String getKey() {
		return key;
	}

	public void setKey(String value) {
		this.key = value;
	}

	public String getName() {
		return name;
	}

	public void setName(String value) {
		this.name = value;
	}

	public String getType() {
		return type;
	}

	public void setType(String value) {
		this.type = value;
	}

	@Override
	public String toString() {
		return "Attribute[name=" + name + ", type=" + type + ", key=" + key + ", isArray=" + getIsArray() + "]";
	}
}
